import { CreateDateColumn, PrimaryGeneratedColumn, UpdateDateColumn } from 'typeorm';
import { ApiProperty } from '@nestjs/swagger';

/**
 * Shared columns for every entity in the platform: a UUID primary key plus
 * created/updated timestamps.
 */
export abstract class AbstractEntity {
  @ApiProperty({ description: 'Primary key (UUID v4), generated by the database.', example: 'b3f1c9a0-6e1a-4b3a-8c7e-2f9a1d4e5c6b', format: 'uuid' })
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @ApiProperty({ description: 'Timestamp the row was created, in UTC.', example: '2026-08-01T09:30:00.000Z', format: 'date-time' })
  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt: Date;

  @ApiProperty({ description: 'Timestamp the row was last updated, in UTC.', example: '2026-08-20T14:05:00.000Z', format: 'date-time' })
  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  updatedAt: Date;
}
